config/routes.rb
MembersCurrency::Application.routes.draw do
  root to: 'members#index'
  resources :members
  resources :currencies
  resources :log_for_currencies
  resources :money_tickets

  get '/login/:member_id', to: 'members#login', as: :login
  get '/logout', to: 'members#logout', as: :logout
  get '/member/give/:from_id/:to_id/:currency_id', to: 'members#confirm_to_give', as: :confirm_give
  post '/member/give/:from_id/:to_id/:currency_id', to: 'members#give', as: :give
  get '/currency/publish/:currency_id', to: 'currencies#publish', as: :currency_publish
  post '/currency/publish/:currency_id', to: 'currencies#add_amount', as: :post_currency_publish
  get '/money_ticket/exchange', to: 'money_tickets#exchange', as: :exchange_point
  post '/money_ticket/exchange', to: 'money_tickets#confirm_exchange', as: :confirm_exchange
  post '/money_ticket/use', to: 'money_tickets#use', as: :use_point
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  attr_accessible :currency_id, :name, :publisher, :unit

  validates :name, presence: true, length: {maximum: 255}
  validates :unit, presence: true, length: {maximum: 50}

  class << self
    def get(currency_id)
      Currency.find(:first, conditions: {currency_id: currency_id})
    end
  end

  def load_data(params)
    self.name = params[:name]
    self.unit = params[:unit]
    self
  end

  def set_publisher(member_id)
    self.publisher = member_id
    self
  end

  def generate_currency_id
    self.currency_id = Currency.all.max{|a, b| a.currency_id <=> b.currency_id}.currency_id + 1
    self
  end

  def distribution
    distributed_currency = LogForCurrency.find(:all, conditions: {currency_id: self.currency_id})
    distributed_currency.inject(0) do |sum, log|
      sum += log.amount
    end
  end

  def invalid?
    super
  end

  def deletable?(member_id)
    return false if member_id.nil?
    member_id == self.publisher && self.circulation_zero?
  end

  def circulation_zero?
    self.distribution.zero? and LogForCurrency.find(:all, conditions: {currency_id: self.currency_id}).empty?
  end

  def publisher_name
    Member.get(self.publisher).name
  end

  def save
    super

    Member.all.each do |member|
      amount = AmountOfCurrency.new
      amount.member_id = member.member_id
      amount.currency_id = self.currency_id
      amount.amount = 0
      amount.save
    end
  end

  def add(amount)
    add_amount = AmountChange.new(:add, amount)
    add_amount
  end

  class AmountChange
    attr_accessor :type, :amount, :currency, :publisher, :members, :amount_per_member

    def initialize(type, amount)
      self.type = type
      self.amount = amount
    end

    def of(currency)
      self.currency = currency
      self
    end

    def to(members)
      self.members = members
      self
    end

    def per(amount_per_member)
      self.amount_per_member = amount_per_member
      self
    end

    def by(publisher)
      self.publisher = publisher
      self
    end

    def run
      self.members.each_with_index do |member_id, index|
        member = Member.get(member_id)
        member_amount = self.amount_per_member[index]
        register_log(member, member_amount)
        add_amount_to_member(member, member_amount)
      end

      true
    end

    private
    def add_amount_to_member(to_member, member_amount)
      amount_of_currency = AmountOfCurrency.get(to_member.member_id, currency.currency_id)
      amount_of_currency.amount += member_amount.to_i

      amount_of_currency.save
    end

    def register_log(member, member_amount)
      log = LogForCurrency.new
      log.currency_id = self.currency.currency_id
      log.from_member_id = LogForCurrency::SYSTEM_ID
      log.to_member_id = member.member_id
      log.amount = member_amount.to_i
      log.operation_date = DateTime.current
      log.log = operation_log(member)

      log.save
    end

    def operation_log(member = nil)
      case self.type
      when :add
        I18n.t('message.distribute', publisher: self.publisher.name, currency: self.currency.name, amount: self.amount, name: member.name)
      end
    end
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  def index
    @currenies = Currency.all
  end

  def show
    @currency = Currency.find(:first, conditions: {id: params[:id]})
    @logs = LogForCurrency.find(
      :all,
      conditions: {
        currency_id: @currency.currency_id
      },
      order: 'operation_date desc'
    )
  end

  def new
    @currency = Currency.new
  end

  def create
    currency = Currency.new.load_data(params[:currency])
    currency.set_publisher(get_login_member_id).generate_currency_id

    if currency.invalid?
      @currency = currency
      flash.now[:error] = t('message.invalid_message')
      render :new and return
    end

    currency.save
    redirect_to currency
  end

  def destroy
    primary_key = params[:id]
    currency = Currency.find(:first, conditions: {id: primary_key})

    unless currency.deletable?
      logger.warn "Illegal access! Delete #{currency.name}."
      flash[:error] = "Illegal operation!! Use normally."
      redirect_to currencies_path and return
    end

    logger.info "Delete #{currency.name} of currency."
    currency.delete
    redirect_to currencies_path
  end

  def publish
    @currency = Currency.get(params[:currency_id])
  end

  def add_amount
    publisher = Member.get(get_login_member_id)
    currency = Currency.get(params[:currency_id])
    amount = params[:add_amount]
    distribution_members = params[:distribution_members]
    amount_per_member = params[:member_amount]

    currency.add(amount).of(currency).to(distribution_members).per(amount_per_member).by(publisher).run

    flash[:notice] = t('message.publish')
    redirect_to currency
  rescue Exception => ex
    flash.now[:alert] = t('message.error')
    logger.warn ex
    logger.warn ex.backtrace

    @currency = currency
    render :publish
  end
end

app/views/currencies/index.html.erb
<h1>通貨一覧</h1>

<table class="table">
  <tr>
    <th>通貨名</th>
    <th>発行者</th>
    <td>流通量</th>
    <td></td>
  </tr>
  <% @currenies.each do |currency| %>
  <tr>
    <td><%= link_to currency.name, currency %></td>
    <td><%= currency.publisher_name %></td>
    <td><%= currency_distribution_with_unit(currency) %></td>
    <td><%= delete_currency_link(currency) %></td>
  </tr>
  <% end %>
</table>

<% if @login_now && login_member.non_publish? %>
  <form method="GET" action="<%= new_currency_path %>">
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">新規に通貨を発行する！</button>
    </div>
  </form>
<% end %>

app/views/currencies/new.html.erb
<%= form_for @currency, html: {class: 'form-horizontal'} do |f| %>
  <fieldset>
    <legend>通貨の新規発行</legend>
    <div class="<%= control_group_class(f, :name) %>">
      <label class="control-label">通貨名</label>
      <div class="controls">
        <%= f.text_field :name, max_length: 255 %>
        <%= error_message(@currency, :name) %>
      </div>
    </div>
    <div class="<%= control_group_class(f, :unit) %>">
      <label class="control-label">通貨単位名</label>
      <div class="controls">
        <%= f.text_field :unit, max_length: 100 %>
        <%= error_message(@currency, :unit) %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">発行者</label>
      <div class="controls">
        <span><%= login_member_name %></span>
    </div>
  </fieldset>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">発行する！</button>
  </div>
<% end %>

app/views/currencies/publish.html.erb
<%= form_for(@currency, html: {class: 'form-horizontal', method: 'POST'}, url: post_currency_publish_path(@currency.currency_id)) do |f| %>
  <fieldset>
    <legend><%= "Add amount of #{@currency.name}" %></legend>
    <div class="control-group">
      <label class="control-label">通貨名</label>
      <div class="controls">
        <span><%= @currency.name %></span>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">発行者</label>
      <div class="controls">
        <span><%= @currency.publisher_name %></span>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">単位名</label>
      <div class="controls">
        <span><%= @currency.unit %></label>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">現在の総流通量</label>
      <div class="controls">
        <span><%= @currency.distribution %></label>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">追加流通量</label>
      <div class="controls">
        <span><input id="add_amount" type="number" class="input-medium" name="add_amount" placeholder="0"></span>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <button id="distribution_button" type="button" class="btn">追加分の分配を決める</button>
      </div>
    </div>
    <div id="distribution_member" class="hide">
      <div class="control-group">
        <label class="control-label">分配先メンバー</label>
        <div class="controls">
          <select name="[distribution_members][]" class="input-medium">
            <%= get_member_list %>
          </select>
          &nbsp;&nbsp;
          <input type="number" class="input-medium member_amount" name="[member_amount][]" placeholder="0">
          &nbsp;&nbsp;
          <button type="button" class="btn remove_member hide" >メンバー削除</button>
        </div><br>
        <div class="controls button_control">
          <button type="button" class="btn add_member">メンバー追加</button>
        </div>
      </div>
      <div class="form-actions">
        <button id="submit_button" type="submit" class="btn btn-primary">発行する！</button>
      </div>
    </div>
  </fieldset>
<% end %>
<script>
  $(function(){
    currency = new Currency();
  });
</script>

app/views/currencies/show.html.erb
<h1><%= @currency.name %> - 通貨詳細</h1>

<div class="currency-detail-tables">
  <ul class="currency-detail">
    <li>
      <table class="table">
        <tr>
          <td>項目</td>
          <td>内容</td>
        </tr>
        <tr>
          <td>通貨管理番号</td>
          <td><%= @currency.currency_id %></td>
        </tr>
        <tr>
          <td>通貨名</td>
          <td><%= @currency.name %></td>
        </tr>
        <tr>
          <td>発行者</td>
          <td><%= @currency.publisher_name %></td>
        </tr>
        <tr>
          <td>単位</td>
          <td><%= @currency.unit %></td>
        </tr>
        <tr>
          <td>総流通量</td>
          <td><%= number_with_delimiter(@currency.distribution) %></td>
        </tr>
      </table>
    </li>
    <li>
      <% if @login_now and @currency.publisher == login_member.member_id %>
      <form method="GET" action="<%= currency_publish_path(@currency.currency_id) %>">
        <button type="submit" class="btn btn-primary"><%= "#{@currency.name}の流通を増やす！" %></button>
      </form>
      <% end %>
    </li>
    <li>
      <%= render 'shared/log_list', logs: @logs %>
    </li>
  </ul>
</div>