config/routes.rb
MembersCurrency::Application.routes.draw do
  root to: 'members#index'
  resources :members
  resources :currencies
  resources :log_for_currencies
  resources :money_tickets

  get '/login/:member_id', to: 'members#login', as: :login
  get '/logout', to: 'members#logout', as: :logout
  get '/member/give/:from_id/:to_id/:currency_id', to: 'members#confirm_to_give', as: :confirm_give
  post '/member/give/:from_id/:to_id/:currency_id', to: 'members#give', as: :give
  get '/currency/publish/:currency_id', to: 'currencies#publish', as: :currency_publish
  post '/currency/publish/:currency_id', to: 'currencies#add_amount', as: :post_currency_publish
  get '/money_ticket/exchange', to: 'money_tickets#exchange', as: :exchange_point
  post '/money_ticket/exchange', to: 'money_tickets#confirm_exchange', as: :confirm_exchange
  post '/money_ticket/use', to: 'money_tickets#use', as: :use_point
end

app/models/money_ticket.rb
class MoneyTicket < ActiveRecord::Base
  attr_accessible :amount, :currency_id, :ticket_id, :status, :used_date, :expire_date

  validates :ticket_id, presence: true, length: {maximum: 30}
  validates :amount, presence: true, numericality: true

  NO_USE = 'NO_USE'
  USED = 'USED'

  class << self
    def exchange_tickets(amount)
      raise Exception.new('Invalid amount!!') if invalid_amount?(amount)

      no_use_tickets = MoneyTicket.find(
        :all,
        conditions: [
          'status = ? AND expire_date > ?',
          NO_USE, DateTime.current
        ],
        order: 'expire_date asc, amount desc'
      ).select{|ticket|
        ticket.amount < amount
      }

      to_use_tickets = no_use_tickets.select{|ticket|
        next if amount.zero?
        if amount - ticket.amount < 0
          next
        end
        amount -= ticket.amount
        true
      }
      raise Exception.new('Ticket is insufficient!!') unless amount.zero?
      to_use_tickets
    end

    def invalid_amount?(amount)
      amount % 500 != 0
    end
  end

  def load_data(params)
    self.ticket_id = params[:ticket_id]
    self.amount = params[:amount]
    self
  end

  def set_default_value
    self.status = NO_USE
    self.used_date = nil
    self
  end

  def get_status
    case self.status
    when NO_USE
      'No used'
    when USED
      'Used'
    end
  end

  def get_used_date
    return '-' if self.used_date.nil?
    self.used_date
  end
end

app/controllers/money_tickets_controller.rb
class MoneyTicketsController < ApplicationController
  def index
    @tickets = MoneyTicket.find(:all, order: 'expire_date asc')
  end

  def new
    @ticket = MoneyTicket.new
    @ticket.expire_date ||= DateTime.current.next_year
  end

  def create
    # Insert params at new is for datetime.
    ticket = MoneyTicket.new(params[:money_ticket]).load_data(params[:money_ticket])
    ticket.set_default_value

    if ticket.invalid?
      @ticket = ticket
      flash.now[:error] = t('message.invalid_message')
      render :new and return
    end

    ticket.save

    redirect_to money_tickets_path
  end

  def exchange
    redirect_to members_path and return unless login?

    @currencies = Currency.all
    @amounts = AmountOfCurrency.find(:all, conditions: {member_id: get_login_member_id})
  end

  def confirm_exchange
    redirect_to members_path and return unless login?

    @currency = Currency.get(params[:exchange][:currency])
    @amount = AmountOfCurrency.new
    @amount.amount = params[:exchange][:amount]
  end

  def use
    redirect_to members_path and return unless login?

    if params[:cancel]
      redirect_to exchange_point_path and return
    end

    exchange_currency_id = params[:exchange][:currency]
    exchange_amount = params[:exchange][:amount].to_i

    login_member = Member.get(get_login_member_id)

    amount_of_member = AmountOfCurrency.get(login_member.member_id, exchange_currency_id)

    if amount_of_member.amount < exchange_amount
      flash[:error] = t('message.less_amount_for_exchange')
      logger.warn "Error!! Illegal exchange. currency:#{exchange_currency_id}, member:#{login_member.member_id}, amount:#{exchange_amount}"
      redirect_to login_member and return
    end

    begin
      login_member.exchange(exchange_amount).of(exchange_currency_id).run
    rescue Exception => ex
      logger.warn ex
      logger.debug ex.backtrace
      flash[:alert] = t('message.ticket_insufficient')
      redirect_to login_member and return
    end

    flash[:notice] = t('message.success_exchange', currency: Currency.get(exchange_currency_id).name, amount: exchange_amount)
    redirect_to login_member and return
  end

  private
  def consistent_exchange?
    true
  end
end

app/helpers/money_tickets_helper.rb
module MoneyTicketsHelper
  def currency_options(currencies)
    currencies.map {|currency|
      <<-TAG
      <option value="#{currency.currency_id}">#{currency.name}</option>
      TAG
    }.join("\n").html_safe
  end

  def ticket_amount_all(tickets)
    tickets.inject(0) do |sum, ticket|
      sum + ticket.amount
    end
  end

  def ticket_amount_no_use(tickets)
    tickets.inject(0) do |sum, ticket|
      if ticket.status == MoneyTicket::NO_USE
        sum + ticket.amount
      else
        sum
      end
    end
  end

  def ticket_amount_exchanged(tickets)
    tickets.inject(0) do |sum, ticket|
      if ticket.status == MoneyTicket::USED
        sum + ticket.amount
      else
        sum
      end
    end
  end

  def ticket_register?(member)
    return false unless Currency.find(:first, conditions: {publisher: member.member_id})
    true
  end
end

app/views/money_tickets/confirm_exchange.html.erb
<%= form_tag({controller: 'money_tickets', action: 'use'}, class: 'form-horizontal') do |f| %>
  <fieldset>
    <legend>換金</legend>
    <div class="control-group">
      <label class="control-label">換金対象の通貨</label>
      <div class="controls">
        <p><%= @currency.name %></p>
        <input type="hidden" name="[exchange][currency]" value="<%= @currency.currency_id %>">
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">換金額</label>
      <div class="controls">
        <p><%= @amount.amount %></p>
        <input type="hidden" name="[exchange][amount]" value="<%= @amount.amount %>">
      </div>
    </div>
  </fieldset>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">換金する！</button>&nbsp;
    <button id="cancel" type="button" class="btn">戻る</button>
  </div>
<% end %>
<script>
  $(function(){
    exchaneg = new Exchange();
  });
</script>

app/views/money_tickets/exchange.html.erb
<%= form_tag({controller: 'money_tickets', action: 'confirm_exchange'}, class: 'form-horizontal') do |f| %>
  <fieldset>
    <legend>換金</legend>
    <div class="control-group">
      <label class="control-label">換金対象の通貨</label>
      <div class="controls">
        <select id="exchange_currency" name="[exchange][currency]">
          <%= currency_options(@currencies) %>
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">換金額</label>
      <div id="amount_selection" class="controls">
        <% @amounts.each do |amount| %>
          <select id="amount_of_<%= amount.currency_id %>" class="hide" name="[exchange][amount]">
            <%= get_amount_of_500_per_options(amount.amount) %>
          </select>
        <% end %>
      </div>
    </div>
  </fieldset>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">換金確認画面へ</button>
  </div>
<% end %>

<script>
  $(function(){
    exchaneg = new Exchange();
  });
</script>

app/views/money_tickets/index.html.erb
<h1>お金チケット一覧</h1>

<form class="form-horizontal">
<div class="control-group">
  <label class="control-label">登録総額</label>
  <div class="controls">
    <p><%= ticket_amount_all(@tickets) %></p>
  </div>
</div>
<div class="control-group">
  <label class="control-label">換金総額</label>
  <div class="controls">
    <p><%= ticket_amount_exchanged(@tickets) %></p>
  </div>
</div>
<div class="control-group">
  <label class="control-label">未使用総額</label>
  <div class="controls">
    <p><%= ticket_amount_no_use(@tickets) %></p>
  </div>
</div>
</form>

<% if @login_now && ticket_register?(login_member) %>
  <form method="GET" action="<%= new_money_ticket_path %>">
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">チケットの新規登録</button>
    </div>
  </form>
<% end %>


</div>
<table class="table">
  <tr>
    <th>チケット番号</th>
    <th>金額</th>
    <th>ステータス</th>
    <th>使用期限</th>
    <th>使用日時</th>
  </tr>
  <% @tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.ticket_id %></td>
      <td><%= ticket.amount %></td>
      <td><%= ticket.get_status %></td>
      <td><%= ticket.expire_date %></td>
      <td><%= ticket.get_used_date %></td>
  <% end %>
</table>

app/views/money_tickets/new.html.erb
<%= form_for @ticket, html: {class: 'form-horizontal'} do |f| %>
  <fieldset>
    <legend>お金チケットの追加登録</legend>
    <div class="<%= control_group_class(f, :ticket_id) %>">
      <label class="control-label">チケット番号</label>
      <div class="controls">
        <%= f.text_field :ticket_id %>
        <%= error_message(@ticket, :ticket_id) %>
      </div>
    </div>
    <div class="<%= control_group_class(f, :amount) %>">
      <label class="control-label">金額</label>
      <div class="controls">
        <%= f.number_field :amount %>
        <%= error_message(@ticket, :amount) %>
      </div>
    </div>
    <div class="<%= control_group_class(f, :expire_date) %>">
      <label class="control-label">使用期限</label>
      <div class="controls">
        <%= f.datetime_select :expire_date, {}, {class: 'span1'} %>
        <%= error_message(@ticket, :expire_date) %>
      </div>
    </div>
  </fieldset>
  <div class="conrols">
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">登録する！</button>
    </div>
  </div>
<% end %>