config/routes.rb
MembersCurrency::Application.routes.draw do
  root to: 'members#index'
  resources :members
  resources :currencies
  resources :log_for_currencies
  resources :money_tickets

  get '/login/:member_id', to: 'members#login', as: :login
  get '/logout', to: 'members#logout', as: :logout
  get '/member/give/:from_id/:to_id/:currency_id', to: 'members#confirm_to_give', as: :confirm_give
  post '/member/give/:from_id/:to_id/:currency_id', to: 'members#give', as: :give
  get '/currency/publish/:currency_id', to: 'currencies#publish', as: :currency_publish
  post '/currency/publish/:currency_id', to: 'currencies#add_amount', as: :post_currency_publish
  get '/money_ticket/exchange', to: 'money_tickets#exchange', as: :exchange_point
  post '/money_ticket/exchange', to: 'money_tickets#confirm_exchange', as: :confirm_exchange
  post '/money_ticket/use', to: 'money_tickets#use', as: :use_point
end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :member_id, :name, :profile
  attr_accessor :currency_list

  validates :name, presence: true, length: {maximum: 255}
  validates :profile, presence: true, length: {maximum: 512}

  class << self
    def get(member_id)
      Member.find(:first, conditions: {member_id: member_id})
    end
  end

  def load_data(params)
    self.name = params[:name]
    self.profile = params[:profile]
    self
  end

  def generate_member_id
    self.member_id = Member.all.max{|a, b| a.member_id <=> b.member_id}.member_id + 1
    self
  end

  def set_currency_info(currency)
    self.currency_list ||= []
    currency_id = currency.currency_id
    currency_information = CurrencyInformation.new
    currency_information.id = currency_id
    currency_information.name = currency.name
    currency_information.amount = AmountOfCurrency.get(self.member_id, currency_id).amount
    self.currency_list.push(currency_information)
    self
  end

  def currency_amount(currency_id)
    currency_info = currency_list.find{|currency| currency.id == currency_id}
    currency_info.amount
  end

  def non_publish?
    Currency.find(:all, conditions: {publisher: self.member_id}).blank?
  end

  def deletable?
    distribution_zero?
  end

  def distribution_zero?
    amounts = AmountOfCurrency.find(:all, conditions: {member_id: self.member_id})
    amounts.all?{|amount| amount.amount.zero?}
  end

  def invalid?
    unless self.distribution_zero?
      self.errors[:error] = 'This data can not delete.'
    end
    super
  end

  def give(given_amount, currency)
    operation = CurrencyOperation.new(self, :give)
    operation.target_currency(currency)
    operation.set_amount(given_amount)
    operation
  end

  def save
    super

    Currency.all.each do |currency|
      amount = AmountOfCurrency.new
      amount.amount = 0
      amount.currency_id = currency.currency_id
      amount.member_id = self.member_id
      amount.save
    end
  end

  def exchange(amount)
    exchange_currency = ExchangeCurrency.new(self.member_id, amount)
    exchange_currency
  end

  class CurrencyInformation
    attr_accessor :id
    attr_accessor :name
    attr_accessor :amount
  end

  class CurrencyOperation
    attr_accessor :type, :from, :currency, :to_member, :amount

    def initialize(from_member, type)
      self.from = from_member
      self.type = type
    end

    def target_currency(currency)
      self.currency = currency
    end

    def set_amount(amount)
      self.amount = amount
    end

    def to(member)
      self.to_member = member
      self
    end

    def run
      ## TODO: Add trunsaction code.
      log = LogForCurrency.new
      log.currency_id = self.currency.currency_id
      log.from_member_id = self.from.member_id
      log.to_member_id = self.to_member.member_id
      log.amount = self.amount
      log.operation_date = DateTime.current
      log.log = operation_log

      log.save

      from_amount = AmountOfCurrency.get(self.from.member_id, self.currency.currency_id)
      from_amount.amount -= self.amount.to_i
      from_amount.save

      to_amount = AmountOfCurrency.get(self.to_member.member_id, self.currency.currency_id)
      to_amount.amount += self.amount.to_i
      to_amount.save

      true
    end

    def operation_log
      case self.type
      when :give
        I18n.t('message.give', from: self.from.name, to: self.to_member.name, currency: self.currency.name, amount:self.amount)
      end
    end
  end

  class ExchangeCurrency
    attr_accessor :currency_id, :member_id, :amount

    def initialize(member_id, amount)
      self.member_id = member_id
      self.amount = amount
    end

    def of(currency_id)
      self.currency_id = currency_id
      self
    end

    def run
      member = Member.get(self.member_id)
      currency = Currency.get(self.currency_id)
      ticket_list = MoneyTicket.exchange_tickets(self.amount)

      ticket_list.each do |ticket|
        ticket.status = MoneyTicket::USED
        ticket.used_date = DateTime.current
        ticket.save
      end

      log = LogForCurrency.new
      log.from_member_id = LogForCurrency::SYSTEM_ID
      log.to_member_id = self.member_id
      log.amount = self.amount
      log.operation_date = DateTime.current
      log.currency_id = self.currency_id
      log.log = I18n.t('log.exchange', name: member.name, currency: currency.name, amount: self.amount)
      log.save

      member_amount = AmountOfCurrency.get(self.member_id, self.currency_id)
      member_amount.amount -= self.amount
      member_amount.save
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
    @members = Member.all
  end

  def show
    @member = Member.find(:first, conditions: {id: params[:id]})
    currency_list = Currency.all
    currency_list.each do |currency|
      @member.set_currency_info(currency)
    end
  end

  def new
    @member = Member.new
  end

  def create
    member = Member.new.load_data(params[:member])
    member.generate_member_id

    if member.invalid?
      @member = member
      flash.now[:error] = t('message.invalid_message')
      render :new and return
    end

    member.save
    redirect_to member
  end

  def destroy
    primary_key = params[:id]
    member = Member.find(:first, conditions: {id: primary_key})

    unless member.deletable?
      logger.warn "Illegal access! Delete #{member.name}."
      flash[:error] = "Illegal operation!! Use normally."
      redirect_to members_path and return
    end

    logger.info "Delete #{member.name} of member."
    member.delete
    redirect_to members_path
  end

  def login
    member_id = params[:member_id]
    login_member = Member.get(member_id)
    save_login(login_member.member_id)

    redirect_to members_path
  end

  def logout
    reset_by_logout
    redirect_to members_path
  end

  def confirm_to_give
    @currency = Currency.get(params[:currency_id])
    @to_member = Member.get(params[:to_id])
    @from_member = Member.get(params[:from_id])

    @to_member.set_currency_info(@currency)
    @from_member.set_currency_info(@currency)
  end

  def give
    currency = Currency.get(params[:currency_id])
    to_member = Member.get(params[:to_id])
    from_member = Member.get(params[:from_id])
    given_amount = params[:given_amount]

    from_member.give(given_amount, currency).to(to_member).run

    redirect_to member_path(to_member.id)
  end
end

app/helpers/members_helper.rb
module MembersHelper
  def login_link(login_now, member)
    login_now ? t('content.member.login_now') : link_to(t('content.member.login'), login_path(member.member_id))
  end

  def give_page_link(to_member, currency_information)
    return "-" if login_member.member_id == to_member.member_id

    from_member = login_member
    link_to(
      t('content.member.presetn', name: to_member.name, currency: currency_information.name),
      confirm_give_path(from_member.member_id, to_member.member_id, currency_information.id)
    )
  end

  def get_amount_of_500_per_options_by_member(member, currency)
    get_amount_of_500_per_options(member.currency_amount(currency.currency_id))
  end

  def get_amount_of_500_per_options(max_amount)
    option_tag_list = []
    0.step(max_amount, 500) do |amount|
      option_tag_list.push(
        <<-TAG
        <option value="#{amount}">#{amount}</option>
        TAG
      )
    end
    option_tag_list.join("\n").html_safe
  end

  def create_give_action_path(from, to, currency)
    give_path(
      from.member_id,
      to.member_id,
      currency.currency_id
    )
  end

  def delete_member_link(member)
    member.deletable? ?
      link_to("Delete", member, method: :delete, confirm: t('message.confirm_delete')) :
      '<span class="muted">Delete</span>'.html_safe
  end
end

app/views/members/confirm_to_give.html.erb
<%= form_for(@from_member, html: {class: 'form-horizontal', method: 'POST'}, url: create_give_action_path(@from_member, @to_member, @currency)) do |f| %>
  <fieldset>
    <legend><%= @currency.name %>を <%= @to_member.name %> さんにプレゼント！</legend>
    <div class="control-group">
      <label class="control-label"><%= @to_member.name %> さんが持っている<%= @currency.name %>は</label>
      <div class="controls">
        <span>
          <%= @to_member.currency_amount(@currency.currency_id) %>
          <%= @currency.unit %>
        </span>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">あなたが持っている<%= @currency.name %>は</label>
      <div class="controls">
        <span>
          <%= @from_member.currency_amount(@currency.currency_id) %>
          <%= @currency.unit %>
        </span>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">プレゼントする額は</label>
      <div class="controls">
        <select class="span2" name="given_amount">
          <%= get_amount_of_500_per_options_by_member(@from_member, @currency) %>
        </select>
        <%= @currency.unit %>
      </div>
    </div>
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">プレゼントする！</button>
    </div>
  </fieldset>
<% end %>

app/views/members/index.html.erb
<h1>メンバー一覧</h1>

<table class="table">
  <col class="id" />
  <col class="name" />
  <tr>
    <th>メンバーID</th>
    <th>名前</th>
    <th></th>
    <th></th>
  </tr>
  <% @members.each do |member| %>
  <tr>
    <td><%= member.member_id %></td>
    <td><%= link_to member.name, member %></td>
    <td><%= login_link(@login_now, member) %></td>
    <td><%= delete_member_link(member) %></td>
  </tr>
  <% end %>
</table>

<form method="GET" action="<%= new_member_path %>">
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">メンバーを新規登録</button>
  </div>
</form>

app/views/members/new.html.erb
<%= form_for @member, html: {class: 'form-horizontal'} do |f| %>
  <fieldset>
    <legend>メンバーの新規登録</legend>
    <div class="<%= control_group_class(f, :name) %>">
      <label class="control-label">名前</label>
      <div class="controls">
        <%= f.text_field :name, max_length: 255 %>
        <%= error_message(@member, :name) %>
      </div>
    </div>
    <div class="<%= control_group_class(f, :profile) %>">
      <label class="control-label">プロフィール</label>
      <div class="controls">
        <%= f.text_area :profile, max_length: 512, rows: 5 %>
        <%= error_message(@member, :profile) %>
      </div>
    </div>
  </fieldset>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">登録する！</button>
  </div>
<% end %>

app/views/members/show.html.erb
<h1>メンバー詳細</h1>

<div class="member-detail-information">
  <ul class="member-detail">
    <li>
      <table class="table">
        <tr>
          <th>項目</th>
          <th>内容</th>
        </tr>
        <tr>
          <td>メンバーID</td>
          <td><%= @member.member_id %></td>
        </tr>
        <tr>
          <td>名前</td>
          <td><%= @member.name %></td>
        </tr>
        <tr>
          <td>プロフィール</td>
          <td><%= @member.profile %></td>
        </tr>
      </table>
    </li>

    <li>
      <table class="table">
        <tr>
          <td>通貨名</td>
          <td>持っている量</td>
          <% if @login_now %>
            <td></td>
          <% end %>
        </tr>
        <% @member.currency_list.each do |currency| %>
          <tr>
            <td><%= currency.name %></td>
            <td><%= currency.amount %></td>
            <% if @login_now %>
              <td>
                <%= give_page_link(@member, currency) %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </table>
    </li>
  </ul>

</div>